{
 "title": "Bitcoin Cash (BCH)",
 "tags": [ "bitcoin" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Blocks",
   "type": "stat",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_blocks", "legendFormat": "Blocks" }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(bitcoin_peers)", "legendFormat": "peers" }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "gauge",
   "description": "Number of seconds bitcoind has been running",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bitcoin_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unconfirmed Tx",
   "type": "timeseries",
   "description": "Uncomfirmed transactions in the BCH mempool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "bitcoin_mempool_size", "legendFormat": "Unconfirmed tx" }
   ]
  },
  {
   "title": "Blockchain Size",
   "type": "timeseries",
   "description": "Size of the BCH blockchain on disk",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    { "expr": "bitcoin_size_on_disk", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Difficulty",
   "type": "timeseries",
   "description": "Difficulty value",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "avg(bitcoin_difficulty)", "legendFormat": "difficulty" }
   ]
  },
  {
   "title": "Fees per block",
   "type": "timeseries",
   "description": "BCH sent to miners via tx fees",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "sum(bitcoin_latest_block_fee) by (bitcoin_blocks)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block value",
   "type": "timeseries",
   "description": "Value of the block transactions in BCH.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    { "expr": "bitcoin_latest_block_value", "legendFormat": "BCH" }
   ]
  },
  {
   "title": "Blocksize",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    { "expr": "bitcoin_latest_block_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fees Over 24Hrs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "sum by(bitcoin_blocks) (sum_over_time(bitcoin_latest_block_fee[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Creation Rate",
   "type": "timeseries",
   "description": "Number of blocks created per day using different trailing rates.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "floor(sum(rate(bitcoin_blocks[3h])) * 3600 * 24)",
     "legendFormat": "3h"
    },
    {
     "expr": "floor(sum(rate(bitcoin_blocks[6h])) * 3600 * 24)",
     "legendFormat": "6h"
    },
    {
     "expr": "floor(sum(rate(bitcoin_blocks[12h])) * 3600 * 24)",
     "legendFormat": "12h"
    },
    {
     "expr": "floor(sum(rate(bitcoin_blocks[7d])) * 3600 * 24)",
     "legendFormat": "7d"
    }
   ]
  },
  {
   "title": "Network Hash Rate",
   "type": "timeseries",
   "description": "Estimated network hashes per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "targets": [
    { "expr": "bitcoin_hashps_30", "legendFormat": "30-blk" },
    { "expr": "bitcoin_hashps_60", "legendFormat": "60-blk" },
    { "expr": "bitcoin_hashps_90", "legendFormat": "90-blk" },
    { "expr": "bitcoin_hashps", "legendFormat": "120-blk" }
   ]
  },
  {
   "title": "Chain Branches",
   "type": "timeseries",
   "description": "Number of tips seen in the chain.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "avg(bitcoin_num_chaintips)", "legendFormat": "tips" }
   ]
  },
  {
   "title": "Versions",
   "type": "timeseries",
   "description": "The Bitcoin protocol and server versions.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "avg(bitcoin_protocol_version)", "legendFormat": "protocol" },
    { "expr": "avg(bitcoin_server_version)", "legendFormat": "server" }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "description": "Sent and received traffic rates",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(bitcoin_total_bytes_sent[5m]))",
     "legendFormat": "sent"
    },
    {
     "expr": "-sum(irate(bitcoin_total_bytes_recv[10m]))",
     "legendFormat": "received"
    }
   ]
  }
 ]
}